INFO:app:info msg
INFO:app:info msg
INFO:app:info msg
INFO:app:info msg
INFO:app:info msg
INFO:app:info msg
INFO:app:info msg
INFO:app:info msg
INFO:app:info msg
INFO:app:info msg
INFO:app:info msg
INFO:app:info msg
INFO:app:info msg
INFO:app:info msg
INFO:app:info msg
INFO:app:info msg
INFO:app:info msg
INFO:app:info msg
2023-12-16 16:21:54,923 - INFO - info msg
2023-12-16 16:21:54,929 - INFO - info msg
2023-12-16 16:21:57,481 - INFO - info msg
2023-12-16 16:21:57,481 - INFO - info msg
2023-12-16 16:21:58,740 - INFO - info msg
2023-12-16 16:21:58,740 - INFO - info msg
December 16th 2023: 16:26 - info msg
December 16th 2023: 16:26 - info msg
December 16th 2023: 16:26 - info msg
December 16th 2023: 16:26 - info msg
December 16th 2023: 16:26 - info msg
December 16th 2023: 16:26 - info msg
December 16th 2023: 16:27 info msg
December 16th 2023: 16:27 info msg
December 16th 2023: 16:27 info msg
December 16th 2023: 16:27 info msg
December 16th 2023: 16:27 info msg
December 16th 2023: 16:27 info msg
December 16th 2023: 17:21 info msg
December 16th 2023: 17:21 info msg
December 16th 2023: 17:21 info msg
December 16th 2023: 17:21 info msg
December 16th 2023: 17:21 info msg
December 16th 2023: 17:21 info msg
December 16th 2023: 17:32 info msg
December 16th 2023: 17:32 info msg
December 16th 2023: 17:32 info msg
December 16th 2023: 17:32 info msg
December 16th 2023: 17:32 info msg
December 16th 2023: 17:32 info msg
December 16th 2023: 17:32 info msg
December 16th 2023: 17:32 info msg
December 16th 2023: 17:32 info msg
December 16th 2023: 17:32 info msg
December 16th 2023: 18:09 info msg
December 16th 2023: 18:31 Exception on /get-current-cargo-state [GET]
Traceback (most recent call last):
  File "C:\Users\rjord\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rjord\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rjord\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\rjord\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rjord\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rjord\Documents\cs179_project\r3\server\app.py", line 78, in get_current_cargo_state
    return jsonify(current_cargo_state.toManifest())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rjord\Documents\cs179_project\r3\server\CargoState.py", line 475, in toManifest
    cell = self.ship[row][col]
           ~~~~~~~~~~~~~~^^^^^
IndexError: list index out of range
December 16th 2023: 18:31 Exception on /get-current-cargo-state [GET]
Traceback (most recent call last):
  File "C:\Users\rjord\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rjord\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rjord\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\rjord\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rjord\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rjord\Documents\cs179_project\r3\server\app.py", line 78, in get_current_cargo_state
    return jsonify(current_cargo_state.toManifest())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rjord\Documents\cs179_project\r3\server\CargoState.py", line 475, in toManifest
    cell = self.ship[row][col]
           ~~~~~~~~~~~~~~^^^^^
IndexError: list index out of range
December 16th 2023: 18:34 Exception on /get-current-cargo-state [GET]
Traceback (most recent call last):
  File "C:\Users\rjord\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rjord\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rjord\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\rjord\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rjord\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rjord\Documents\cs179_project\r3\server\app.py", line 78, in get_current_cargo_state
    return jsonify(current_cargo_state.toManifest())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rjord\Documents\cs179_project\r3\server\CargoState.py", line 476, in toManifest
    fWeight = str(cell.weight)
                  ^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'weight'
December 16th 2023: 18:34 Exception on /get-current-cargo-state [GET]
Traceback (most recent call last):
  File "C:\Users\rjord\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rjord\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rjord\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\rjord\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rjord\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rjord\Documents\cs179_project\r3\server\app.py", line 78, in get_current_cargo_state
    return jsonify(current_cargo_state.toManifest())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rjord\Documents\cs179_project\r3\server\CargoState.py", line 476, in toManifest
    fWeight = str(cell.weight)
                  ^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'weight'
December 16th 2023: 18:35 Exception on /get-current-cargo-state [GET]
Traceback (most recent call last):
  File "C:\Users\rjord\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rjord\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rjord\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\rjord\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rjord\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rjord\Documents\cs179_project\r3\server\app.py", line 78, in get_current_cargo_state
    return jsonify(current_cargo_state.toManifest())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rjord\Documents\cs179_project\r3\server\CargoState.py", line 476, in toManifest
    fWeight = str(cell.weight)
                  ^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'weight'
December 16th 2023: 18:35 Exception on /get-current-cargo-state [GET]
Traceback (most recent call last):
  File "C:\Users\rjord\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rjord\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rjord\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\rjord\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rjord\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rjord\Documents\cs179_project\r3\server\app.py", line 78, in get_current_cargo_state
    return jsonify(current_cargo_state.toManifest())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rjord\Documents\cs179_project\r3\server\CargoState.py", line 476, in toManifest
    fWeight = str(cell.weight)
                  ^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'weight'
